from sqlalchemy import Column, Integer, BigInteger, SmallInteger, String, Numeric, Date, Time
from typing import Optional
from datetime import date, time
from .database import Base


class HeadOfSpecifications(Base):
    __tablename__ = 'ka2450_00105'
    __allow_unmapped__ = True
    
    KA2450_REZ_NR = Column(BigInteger, primary_key=True, nullable=False)
    KA2450_VAR_NR = Column(SmallInteger, primary_key=True, nullable=False)
    KA2450_REZ_OBJ_TYP = Column(SmallInteger, primary_key=True, nullable=False)
    KA2450_REZ_OBJ_NR = Column(BigInteger, primary_key=True, nullable=False)

    KA2450_REZ_AKTIV_VON = Column(Integer, nullable=False)
    KA2450_REZ_AKTIV_BIS = Column(Integer, nullable=False)
    KA2450_ANL_DATUM = Column(Integer, nullable=False)
    KA2450_ANL_ZEIT = Column(Integer, nullable=False)
    KA2450_ANL_USER = Column(Integer, nullable=False)
    KA2450_ANL_STATION = Column(SmallInteger, nullable=False)
    KA2450_ANL_PROG = Column(SmallInteger,nullable=False)
    KA2450_ANL_FKT = Column(Integer, nullable=False)
    KA2450_UPD_DATUM = Column(Integer, nullable=False)
    KA2450_UPD_ZEIT = Column(Integer, nullable=False)
    KA2450_UPD_USER = Column(Integer, nullable=False)
    KA2450_UPD_STATION = Column(SmallInteger, nullable=False)
    KA2450_UPD_PROG = Column(SmallInteger, nullable=False)
    KA2450_UPD_FKT = Column(Integer,nullable=False)
    KA2450_VAR_BEZ = Column(String(50), nullable=False)
    KA2450_REZ_VERANT_USER = Column(Integer, nullable=False)
    KA2450_PROD_KST_NR = Column(BigInteger, nullable=False)
    KA2450_KALK_DATUM = Column(Integer, nullable=False)
    KA2450_KALK_DATUM_NACHK = Column(Integer, nullable=False)
    KA2450_KALK_DATUM_GLOBAL = Column(Integer, nullable=False)
    KA2450_NACHKALK_PROG_NR = Column(SmallInteger,nullable=False)
    KA2450_PROD_ZUL_DATUM_VON = Column(Integer, nullable=False)
    KA2450_PROD_ZUL_DATUM_BIS = Column(Integer, nullable=False)
    KA2450_BEZUGSDATUM_VAR_ERM = Column(Integer, nullable=False)
    KA2450_GES_GEW_SGE = Column(Numeric(18, 6),nullable=False)
    KA2450_GES_GEW_PE_VK = Column(Numeric(18, 6), nullable=False)
    KA2450_GES_GEW_SGE_BRU = Column(Numeric(18, 6), nullable=False)
    KA2450_GES_STUECKZAHL = Column(Numeric(18, 6),nullable=False)
    KA2450_CHAR_GR_PE_VK = Column(Numeric(18, 6), nullable=False)
    KA2450_MIN_CHAR_GR_PE_VK = Column(Numeric(18, 6), nullable=False)
    KA2450_SUM_ANT_MENGE_SGE = Column(Numeric(18, 6), nullable=False)
    KA2450_PREISSTUFE_MAT = Column(SmallInteger, nullable=False)
    KA2450_PREISSTUFE_EIN = Column(SmallInteger, nullable=False)
    KA2450_PREISSTUFE_REN = Column(SmallInteger, nullable=False)
    KA2450_PREISSTUFE_VK = Column(SmallInteger,nullable=False)
    KA2450_SPERRE = Column(SmallInteger, nullable=False)
    KA2450_REZ_TYP = Column(SmallInteger, nullable=False)
    KA2450_STUECK_KALK = Column(SmallInteger, nullable=False)
    KA2450_LINIENFERTIGUNG = Column(SmallInteger, nullable=False)
    KA2450_ALT_PROD_VAR = Column(SmallInteger,nullable=False)
    KA2450_VK_REZ = Column(SmallInteger, nullable=False)
    KA2450_EXPORT_EXTERN = Column(SmallInteger, nullable=False)
    KA2450_KALK_BASIS = Column(SmallInteger,nullable=False)
    KA2450_QUID_BERECHNUNG = Column(SmallInteger, nullable=False)
    KA2450_HERST_DAUER = Column(Numeric(17, 4), nullable=False)
    KA2450_HERST_DAUER_EINMALIG = Column(Numeric(17, 4), nullable=False)
    KA2450_RUEST_DAUER = Column(Numeric(17, 4), nullable=False)
    KA2450_LIEGE_DAUER = Column(Numeric(17, 4), nullable=False)
    KA2450_ZIELTEMPERATUR = Column(Numeric(11, 6),  nullable=False)
    KA2450_TEMP_VERAEND_ABS = Column(Numeric(11, 6),  nullable=False)
    KA2450_TEMP_KORR_FAKTOR = Column(Numeric(11, 6), nullable=False)
    KA2450_LA_STATUS_VERW = Column(SmallInteger,  nullable=False)
    KA2450_LA_STATUS_NR = Column(SmallInteger, nullable=False)
    KA2450_DICHTE = Column(Numeric(11, 6),  nullable=False)
    KA2450_SPEZ_NR = Column(BigInteger, nullable=False)
    KA2450_RKL_AUSPR_NR_1 = Column(BigInteger, nullable=False)
    KA2450_RKL_AUSPR_NR_2 = Column(BigInteger,  nullable=False)
    KA2450_RKL_AUSPR_NR_3 = Column(BigInteger,  nullable=False)
    KA2450_RKL_AUSPR_NR_4 = Column(BigInteger,nullable=False)
    KA2450_RKL_AUSPR_NR_5 = Column(BigInteger, nullable=False)
    KA2450_PROZ_BASIS_MENGE = Column(Numeric(9, 6), nullable=False)
    KA2450_OPT_ART_LST_NR = Column(BigInteger, nullable=False)
    KA2450_CIM_NR = Column(BigInteger, nullable=False)
    KA2450_VERF_NR = Column(BigInteger, nullable=False)
    KA2450_ALT_KST_LST_NR = Column(BigInteger, nullable=False)
    KA2450_ANZ_ETIKETTEN = Column(BigInteger,    nullable=False)
    KA2450_REZ_VERS_NR = Column(BigInteger,   nullable=False)
    KA2450_DET_SPERR_STAT = Column(Integer, nullable=False)
    KA2450_HBK_ZEIT = Column(Numeric(5, 1),  nullable=False)
    KA2450_PREIS_ERM = Column(SmallInteger, nullable=False)
    KA2450_BEZUG_DAT_PREIS_ERM = Column(Integer, nullable=False)
    KA2450_PREISBILDUNG = Column(SmallInteger, nullable=False)
    KA2450_GS_VAR = Column(SmallInteger,nullable=False)
    KA2450_VERS_EXT = Column(BigInteger, nullable=False)
    KA2450_PREIS_FORT_VAR = Column(SmallInteger, nullable=False)
    
    def __repr__(self):
        return f"<HeadOfSpecifications(REZ_NR={self.KA2450_REZ_NR}, VAR_NR={self.KA2450_VAR_NR})>"



class CardOfArticle(Base):
    __tablename__ = "sy0012_00110" 
    SY0012_NR = Column(BigInteger, primary_key=True, nullable=False)
    SY0012_SUCHBEGRIFF = Column(String(20), nullable=False)
    SY0012_ID_NR = Column(String(25), nullable=False)
    SY0012_BEZ1 = Column(String(50), nullable=False)
    SY0012_BEZ2 = Column(String(50), nullable=False)
    SY0012_BEZ3 = Column(String(50), nullable=False)
    SY0012_BEZ4 = Column(String(50), nullable=False)
    SY0012_BEZ5 = Column(String(50), nullable=False)
    SY0012_EK_ME = Column(String(2), nullable=False)
    SY0012_EK_BE = Column(String(2), nullable=False)
    SY0012_VK_ME = Column(String(2), nullable=False)
    SY0012_VK_BE = Column(String(2), nullable=False)
    SY0012_LA_ME = Column(String(2), nullable=False)
    SY0012_BASIS_EINH = Column(String(4), nullable=False)
    SY0012_EH_MENGE_VAR_VK = Column(String(4), nullable=False)
    SY0012_EH_MENGE_VAR_EK = Column(String(4), nullable=False)
    SY0012_STANDARD_EINH_VK = Column(String(4), nullable=False)
    SY0012_STANDARD_EINH_EK = Column(String(4), nullable=False)
    SY0012_LAGER_EINH = Column(String(4), nullable=False)
    SY0012_STANDARD_LOG_VK = Column(String(4), nullable=False)
    SY0012_STANDARD_LOG_EK = Column(String(4), nullable=False)
    SY0012_QUALITAET_KZ = Column(String(5), nullable=False)
    SY0012_HOST_ART_NR = Column(String(13), nullable=False)
    SY0012_UFI = Column(String(30), nullable=False)
    SY0012_FARBCODE = Column(String(20), nullable=False)
    SY0012_UN_VERP_TYP = Column(String(30), nullable=False)
    SY0012_HAUPT_ART = Column(BigInteger, nullable=False)
    SY0012_AUSPR_ART = Column(BigInteger, nullable=False)
    SY0012_WARENGRUPPE = Column(BigInteger, nullable=False)
    SY0012_ANL_DATUM = Column(Integer, nullable=False)
    SY0012_ANL_ZEIT = Column(Integer, nullable=False)
    SY0012_ANL_USER = Column(Integer, nullable=False)
    SY0012_ANL_FKT = Column(Integer, nullable=False)
    SY0012_UPD_DATUM = Column(Integer, nullable=False)
    SY0012_UPD_ZEIT = Column(Integer, nullable=False)
    SY0012_UPD_USER = Column(Integer, nullable=False)
    SY0012_UPD_FKT = Column(Integer, nullable=False)
    SY0012_ART_GRUPPE = Column(BigInteger, nullable=False)
    SY0012_MWST_GRUND = Column(Integer, nullable=False)
    SY0012_VST_GRUND = Column(Integer, nullable=False)
    SY0012_LAGERARTIKEL_NR = Column(BigInteger, nullable=False)
    SY0012_LAGER_NR = Column(BigInteger, nullable=False)
    SY0012_VERSAND_STELLE = Column(BigInteger, nullable=False)
    SY0012_ABGABE_STELLE = Column(BigInteger, nullable=False)
    SY0012_HBK_VAR = Column(BigInteger, nullable=False)
    SY0012_KURVE = Column(Integer, nullable=False)
    SY0012_WARENSEKTOR = Column(Integer, nullable=False)
    SY0012_WARENVERZ_NR = Column(Integer, nullable=False)
    SY0012_ABC_KLASSE = Column(Integer, nullable=False)
    SY0012_ANZ_LAGE = Column(Integer, nullable=False)
    SY0012_ANZ_PRO_LAGE = Column(Integer, nullable=False)
    SY0012_GTIN_VAR = Column(BigInteger, nullable=False)
    SY0012_QUID_REGEL = Column(Integer, nullable=False)
    SY0012_STD_LIEFERANT = Column(BigInteger, nullable=False)
    SY0012_STD_HERSTELLER = Column(BigInteger, nullable=False)
    SY0012_DOK_LENKUNG_NR = Column(BigInteger, nullable=False)
    SY0012_KONFIG_NR = Column(BigInteger, nullable=False)
    SY0012_KALK_BASIS_ART_NR = Column(BigInteger, nullable=False)
    SY0012_PCN_SCHABLONE = Column(BigInteger, nullable=False)
    SY0012_ANL_STATION = Column(SmallInteger, nullable=False)
    SY0012_ANL_PROG = Column(SmallInteger, nullable=False)
    SY0012_UPD_STATION = Column(SmallInteger, nullable=False)
    SY0012_UPD_PROG = Column(SmallInteger, nullable=False)
    SY0012_ART_TYP = Column(SmallInteger, nullable=False) 
    SY0012_WEITERE_EINH = Column(SmallInteger, nullable=False)
    SY0012_TARA = Column(SmallInteger, nullable=False)
    SY0012_MWST = Column(SmallInteger, nullable=False)
    SY0012_VST = Column(SmallInteger, nullable=False)
    SY0012_RUNDE = Column(SmallInteger, nullable=False)
    SY0012_VK_WIEGEN = Column(SmallInteger, nullable=False)
    SY0012_SORTIMENTZWANG = Column(SmallInteger, nullable=False)
    SY0012_ABTROPFGEWICHT = Column(SmallInteger, nullable=False)
    SY0012_TK_ARTIKEL = Column(SmallInteger, nullable=False)
    SY0012_RV_RELEVANT = Column(SmallInteger, nullable=False)
    SY0012_INTRA_FREI = Column(SmallInteger, nullable=False)
    SY0012_GEFAHRGUT = Column(SmallInteger, nullable=False)
    SY0012_WARTUNG = Column(SmallInteger, nullable=False)
    SY0012_BESTAETIGUNG = Column(SmallInteger, nullable=False)
    SY0012_DIENSTLEISTUNG = Column(SmallInteger, nullable=False)
    SY0012_LAGER_ART = Column(SmallInteger, nullable=False)
    SY0012_HBK1_TYP = Column(SmallInteger, nullable=False)
    SY0012_ABW_HBK1 = Column(SmallInteger, nullable=False)
    SY0012_ABW_HBK2 = Column(SmallInteger, nullable=False)
    SY0012_HBK_ZEIT_1_STD = Column(SmallInteger, nullable=False)
    SY0012_TOLERANZ = Column(SmallInteger, nullable=False)
    SY0012_TOLERANZ_OBEN = Column(SmallInteger, nullable=False)
    SY0012_FESTIGKEIT = Column(SmallInteger, nullable=False)
    SY0012_STD_GEBINDE = Column(SmallInteger, nullable=False)
    SY0012_MIM = Column(SmallInteger, nullable=False)
    SY0012_ANWENDER = Column(SmallInteger, nullable=False)
    SY0012_EK_KGME = Column(Numeric(18, 10), nullable=False)
    SY0012_EK_MEBE = Column(Numeric(18, 10), nullable=False)
    SY0012_VK_KGME = Column(Numeric(18, 10), nullable=False)
    SY0012_VK_MEBE = Column(Numeric(18, 10), nullable=False)
    SY0012_LA_KGME = Column(Numeric(18, 10), nullable=False)
    SY0012_LA_KGME_VK = Column(Numeric(18, 10), nullable=False)
    SY0012_VERP_GEW = Column(Numeric(18, 6), nullable=False)
    SY0012_VERP_GEW_PAZ = Column(Numeric(18, 6), nullable=False)
    SY0012_HBK_ZEIT = Column(Numeric(5, 1), nullable=False)
    SY0012_HBK_ZEIT_2 = Column(Numeric(5, 1), nullable=False)
    SY0012_HBK_ZEIT_3 = Column(Numeric(5, 1), nullable=False)
    SY0012_HBK_ZEIT_4 = Column(Numeric(5, 1), nullable=False)
    SY0012_LAENGE = Column(Numeric(18, 6), nullable=False)
    SY0012_HOEHE = Column(Numeric(18, 6), nullable=False)
    SY0012_BREITE = Column(Numeric(18, 6), nullable=False)
    SY0012_VOLUMEN = Column(Numeric(18, 6), nullable=False)
    SY0012_SCHWUND = Column(Numeric(5, 2), nullable=False)
    SY0012_BEF_TEMP = Column(Numeric(7, 3), nullable=False)
    SY0012_LAG_TEMP = Column(Numeric(7, 3), nullable=False)
    SY0012_PREIS_TOL = Column(Numeric(4, 2), nullable=False)


class GroupOfArticle(Base):
    __tablename__ = 'sy8081_00104'
    SY8081_ART_NR = Column(BigInteger, primary_key=True, nullable=False)
    SY8081_SORTGR_TITEL = Column(String(50), primary_key=True, nullable=False) 
    SY8081_DATUM_BIS = Column(Integer, nullable=False)
    SY8081_DATUM_VON = Column(Integer, nullable=False)
    SY8081_SORTGR_NR = Column(BigInteger, nullable=False)
    SY8081_ANL_DATUM = Column(Integer, nullable=False)
    SY8081_ANL_ZEIT = Column(Integer, nullable=False)
    SY8081_ANL_USER = Column(Integer, nullable=False)
    SY8081_ANL_STATION = Column(SmallInteger, nullable=False)
    SY8081_ANL_PROG = Column(SmallInteger, nullable=False)
    SY8081_ANL_FKT = Column(Integer, nullable=False)
    SY8081_UPD_DATUM = Column(Integer, nullable=False)
    SY8081_UPD_ZEIT = Column(Integer, nullable=False)
    SY8081_UPD_USER = Column(Integer, nullable=False)
    SY8081_UPD_STATION = Column(SmallInteger, nullable=False)
    SY8081_UPD_PROG = Column(SmallInteger, nullable=False)
    SY8081_UPD_FKT = Column(Integer, nullable=False)

class BlockedArt(Base):
    __tablename__ = 'sy8212_00104'
    SY8212_ART_NR = Column(BigInteger, primary_key=True, nullable=False)
    SY8212_DATUM_VON = Column(Integer, nullable=False)
    SY8212_DATUM_BIS = Column(Integer, nullable=False)